name: deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: push to gh-pages
      run: |
        git push origin `git subtree split --prefix files master`:gh-pages
